### ISSUE TITLE
Error Cannot read property android of null

### ISSUE THREAD

**Issue by anuragd7** [rhanbIT/nativescript-bottombar#15]
Hi @rhanbIT
Running the project on android I am getting the following error:

Executing before-watch hook from /Users/NRMac/Projects/nativescript/HtmlViewExample/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.0.10
8:21:59 AM - Compilation complete. Watching for file changes.

JS: EXCEPTION: Error in app.component.html:25:23 caused by: Cannot read property 'android' of null
JS: ORIGINAL EXCEPTION: Cannot read property 'android' of null
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'android' of null
JS: at file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:176:82
JS: at Array.forEach (native)
JS: at BottomBar.createItems (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:170:15)
JS: at BottomBar._onItemsPropertyChangedSetNativeValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:165:14)
JS: at PropertyMetadata.itemsProperty.metadata.onSetNativeValue [as _onSetNativeValue] (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/common.js:50:15)
JS: at BottomBar.ProxyObject._trySetNativeValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js:83:27)
JS: at BottomBar.ProxyObject._onPropertyChanged (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js:46:14)
JS: at BottomBar.View._onPropertyChanged (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view-common.js:772:45)
JS: at BottomBar.DependencyObservable._setValueInternal (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:307:18)
JS: at BottomBar.DependencyObservable._setValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:133:14)
JS: ERROR CONTEXT:
JS: [object Object]
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: Error in app.component.html:25:23 caused by: Cannot read property 'android' of null
JS:
JS: TypeError: Cannot read property 'android' of null
JS: at file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:176:82
JS: at Array.forEach (native)
JS: at BottomBar.createItems (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:170:15)
JS: at BottomBar._onItemsPropertyChangedSetNativeValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:165:14)
JS: at PropertyMetadata.itemsProperty.metadata.onSetNativeValue [as _onSetNativeValue] (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/common.js:50:15)
JS: at BottomBar.ProxyObject._trySetNativeValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js:83:27)
JS: at BottomBar.ProxyObject._onPropertyChanged (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js:46:14)
JS: at BottomBar.View._onPropertyChanged (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view-common.js:772:45)
JS: at BottomBar.DependencyObservable._setValueInternal (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:307:18)
JS: at BottomBar.DependencyObservable._setValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:133:14)

**Comment by anuragd7** [comment]
The error was because of the icons not being named correctly in the resources folder. After doing that and tns build android --clean  it runs correclty in android.
